// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjXz4RYW2ptrMgz52JSLKVvRgBRkxBsBc',
    appId: '1:988051786330:web:52f5e9f9c8a75084d46663',
    messagingSenderId: '988051786330',
    projectId: 'rentalcar-51a68',
    authDomain: 'rentalcar-51a68.firebaseapp.com',
    storageBucket: 'rentalcar-51a68.appspot.com',
    measurementId: 'G-98N40S8B68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNvBpOfyxQxOEyrvmfqga0p6-prv8Sljw',
    appId: '1:988051786330:android:b75df472ae476e63d46663',
    messagingSenderId: '988051786330',
    projectId: 'rentalcar-51a68',
    storageBucket: 'rentalcar-51a68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwkaDP-Z1aonTQf9tzg6DNJisY_XWRxzA',
    appId: '1:988051786330:ios:802d26ade28f6ee9d46663',
    messagingSenderId: '988051786330',
    projectId: 'rentalcar-51a68',
    storageBucket: 'rentalcar-51a68.appspot.com',
    iosClientId: '988051786330-omqkasqs1rg77tpmfb42hnuso151fnhg.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentalcar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwkaDP-Z1aonTQf9tzg6DNJisY_XWRxzA',
    appId: '1:988051786330:ios:4df09f3d7c47fa85d46663',
    messagingSenderId: '988051786330',
    projectId: 'rentalcar-51a68',
    storageBucket: 'rentalcar-51a68.appspot.com',
    iosClientId: '988051786330-ded9l1jj4b3769an01sq45ad2efbmt3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentalcar.RunnerTests',
  );
}
